import {
    NE_0_SAME,
    NE_1_UP_UP_CLOCK,
    NE_2_UP_UP_COUNTER,
    NE_3_DOWN_DOWN_CLOCK,
    NE_4_DOWN_DOWN_COUNTER,
    NE_5_FLAT__FLAT,
    NE_6_FLAT__UP,
    NE_7_UP__FLAT,
    NE_8_DOWN__FLAT,
    NE_9_FLAT__DOWN,
    NE_10_UP__UP,
    NE_11_DOWN__DOWN,
    NE_12_UP__DOWN,
    NE_13_DOWN__UP,
    NE_14_BLOCKED,
    NE_15_STROLL_INTO_AIR,
    NE_16_DESCEND_ONE_STEP
} from "../tiles/ne/ne-constants.js";

let ne_move_types = {
    NE_0_SAME: NE_0_SAME,
    NE_1_UP_UP_CLOCK: NE_1_UP_UP_CLOCK,
    NE_2_UP_UP_COUNTER: NE_2_UP_UP_COUNTER,
    NE_3_DOWN_DOWN_CLOCK: NE_3_DOWN_DOWN_CLOCK,
    NE_4_DOWN_DOWN_COUNTER: NE_4_DOWN_DOWN_COUNTER,
    NE_5_FLAT__FLAT: NE_5_FLAT__FLAT,
    NE_6_FLAT__UP: NE_6_FLAT__UP,
    NE_7_UP__FLAT: NE_7_UP__FLAT,
    NE_8_DOWN__FLAT: NE_8_DOWN__FLAT,
    NE_9_FLAT__DOWN: NE_9_FLAT__DOWN,
    NE_10_UP__UP: NE_10_UP__UP,
    NE_11_DOWN__DOWN: NE_11_DOWN__DOWN,
    NE_12_UP__DOWN: NE_12_UP__DOWN,
    NE_13_DOWN__UP: NE_13_DOWN__UP,
    NE_14_BLOCKED: NE_14_BLOCKED,
    NE_15_STROLL_INTO_AIR: NE_15_STROLL_INTO_AIR,
    NE_16_DESCEND_ONE_STEP: NE_16_DESCEND_ONE_STEP
};

import {
    NN_0_SAME,
    NN_1_UP_UP_CLOCK,
    NN_2_UP_UP_COUNTER,
    NN_3_DOWN_DOWN_CLOCK,
    NN_4_DOWN_DOWN_COUNTER,
    NN_5_FLAT__FLAT,
    NN_6_FLAT__UP,
    NN_7_UP__FLAT,
    NN_8_DOWN__FLAT,
    NN_9_FLAT__DOWN,
    NN_10_UP__UP,
    NN_11_DOWN__DOWN,
    NN_12_UP__DOWN,
    NN_13_DOWN__UP,
    NN_14_BLOCKED,
    NN_15_STROLL_INTO_AIR,
    NN_16_DESCEND_ONE_STEP
} from "../tiles/nn/nn-constants.js";

let nn_move_types = {
    NN_0_SAME: NN_0_SAME,
    NN_1_UP_UP_CLOCK: NN_1_UP_UP_CLOCK,
    NN_2_UP_UP_COUNTER: NN_2_UP_UP_COUNTER,
    NN_3_DOWN_DOWN_CLOCK: NN_3_DOWN_DOWN_CLOCK,
    NN_4_DOWN_DOWN_COUNTER: NN_4_DOWN_DOWN_COUNTER,
    NN_5_FLAT__FLAT: NN_5_FLAT__FLAT,
    NN_6_FLAT__UP: NN_6_FLAT__UP,
    NN_7_UP__FLAT: NN_7_UP__FLAT,
    NN_8_DOWN__FLAT: NN_8_DOWN__FLAT,
    NN_9_FLAT__DOWN: NN_9_FLAT__DOWN,
    NN_10_UP__UP: NN_10_UP__UP,
    NN_11_DOWN__DOWN: NN_11_DOWN__DOWN,
    NN_12_UP__DOWN: NN_12_UP__DOWN,
    NN_13_DOWN__UP: NN_13_DOWN__UP,
    NN_14_BLOCKED: NN_14_BLOCKED,
    NN_15_STROLL_INTO_AIR: NN_15_STROLL_INTO_AIR,
    NN_16_DESCEND_ONE_STEP: NN_16_DESCEND_ONE_STEP
};

import {
    NW_0_SAME,
    NW_1_UP_UP_CLOCK,
    NW_2_UP_UP_COUNTER,
    NW_3_DOWN_DOWN_CLOCK,
    NW_4_DOWN_DOWN_COUNTER,
    NW_5_FLAT__FLAT,
    NW_6_FLAT__UP,
    NW_7_UP__FLAT,
    NW_8_DOWN__FLAT,
    NW_9_FLAT__DOWN,
    NW_10_UP__UP,
    NW_11_DOWN__DOWN,
    NW_12_UP__DOWN,
    NW_13_DOWN__UP,
    NW_14_BLOCKED,
    NW_15_STROLL_INTO_AIR,
    NW_16_DESCEND_ONE_STEP
} from "../tiles/nw/nw-constants.js";

let nw_move_types = {
    NW_0_SAME: NW_0_SAME,
    NW_1_UP_UP_CLOCK: NW_1_UP_UP_CLOCK,
    NW_2_UP_UP_COUNTER: NW_2_UP_UP_COUNTER,
    NW_3_DOWN_DOWN_CLOCK: NW_3_DOWN_DOWN_CLOCK,
    NW_4_DOWN_DOWN_COUNTER: NW_4_DOWN_DOWN_COUNTER,
    NW_5_FLAT__FLAT: NW_5_FLAT__FLAT,
    NW_6_FLAT__UP: NW_6_FLAT__UP,
    NW_7_UP__FLAT: NW_7_UP__FLAT,
    NW_8_DOWN__FLAT: NW_8_DOWN__FLAT,
    NW_9_FLAT__DOWN: NW_9_FLAT__DOWN,
    NW_10_UP__UP: NW_10_UP__UP,
    NW_11_DOWN__DOWN: NW_11_DOWN__DOWN,
    NW_12_UP__DOWN: NW_12_UP__DOWN,
    NW_13_DOWN__UP: NW_13_DOWN__UP,
    NW_14_BLOCKED: NW_14_BLOCKED,
    NW_15_STROLL_INTO_AIR: NW_15_STROLL_INTO_AIR,
    NW_16_DESCEND_ONE_STEP: NW_16_DESCEND_ONE_STEP
};

import {
    SE_0_SAME,
    SE_1_UP_UP_CLOCK,
    SE_2_UP_UP_COUNTER,
    SE_3_DOWN_DOWN_CLOCK,
    SE_4_DOWN_DOWN_COUNTER,
    SE_5_FLAT__FLAT,
    SE_6_FLAT__UP,
    SE_7_UP__FLAT,
    SE_8_DOWN__FLAT,
    SE_9_FLAT__DOWN,
    SE_10_UP__UP,
    SE_11_DOWN__DOWN,
    SE_12_UP__DOWN,
    SE_13_DOWN__UP,
    SE_14_BLOCKED,
    SE_15_STROLL_INTO_AIR,
    SE_16_DESCEND_ONE_STEP
} from "../tiles/se/se-constants.js";

let se_move_types = {
    SE_0_SAME: SE_0_SAME,
    SE_1_UP_UP_CLOCK: SE_1_UP_UP_CLOCK,
    SE_2_UP_UP_COUNTER: SE_2_UP_UP_COUNTER,
    SE_3_DOWN_DOWN_CLOCK: SE_3_DOWN_DOWN_CLOCK,
    SE_4_DOWN_DOWN_COUNTER: SE_4_DOWN_DOWN_COUNTER,
    SE_5_FLAT__FLAT: SE_5_FLAT__FLAT,
    SE_6_FLAT__UP: SE_6_FLAT__UP,
    SE_7_UP__FLAT: SE_7_UP__FLAT,
    SE_8_DOWN__FLAT: SE_8_DOWN__FLAT,
    SE_9_FLAT__DOWN: SE_9_FLAT__DOWN,
    SE_10_UP__UP: SE_10_UP__UP,
    SE_11_DOWN__DOWN: SE_11_DOWN__DOWN,
    SE_12_UP__DOWN: SE_12_UP__DOWN,
    SE_13_DOWN__UP: SE_13_DOWN__UP,
    SE_14_BLOCKED: SE_14_BLOCKED,
    SE_15_STROLL_INTO_AIR: SE_15_STROLL_INTO_AIR,
    SE_16_DESCEND_ONE_STEP: SE_16_DESCEND_ONE_STEP
};

import {
    SS_0_SAME,
    SS_1_UP_UP_CLOCK,
    SS_2_UP_UP_COUNTER,
    SS_3_DOWN_DOWN_CLOCK,
    SS_4_DOWN_DOWN_COUNTER,
    SS_5_FLAT__FLAT,
    SS_6_FLAT__UP,
    SS_7_UP__FLAT,
    SS_8_DOWN__FLAT,
    SS_9_FLAT__DOWN,
    SS_10_UP__UP,
    SS_11_DOWN__DOWN,
    SS_12_UP__DOWN,
    SS_13_DOWN__UP,
    SS_14_BLOCKED,
    SS_15_STROLL_INTO_AIR,
    SS_16_DESCEND_ONE_STEP
} from "../tiles/ss/ss-constants.js";

let ss_move_types = {
    SS_0_SAME: SS_0_SAME,
    SS_1_UP_UP_CLOCK: SS_1_UP_UP_CLOCK,
    SS_2_UP_UP_COUNTER: SS_2_UP_UP_COUNTER,
    SS_3_DOWN_DOWN_CLOCK: SS_3_DOWN_DOWN_CLOCK,
    SS_4_DOWN_DOWN_COUNTER: SS_4_DOWN_DOWN_COUNTER,
    SS_5_FLAT__FLAT: SS_5_FLAT__FLAT,
    SS_6_FLAT__UP: SS_6_FLAT__UP,
    SS_7_UP__FLAT: SS_7_UP__FLAT,
    SS_8_DOWN__FLAT: SS_8_DOWN__FLAT,
    SS_9_FLAT__DOWN: SS_9_FLAT__DOWN,
    SS_10_UP__UP: SS_10_UP__UP,
    SS_11_DOWN__DOWN: SS_11_DOWN__DOWN,
    SS_12_UP__DOWN: SS_12_UP__DOWN,
    SS_13_DOWN__UP: SS_13_DOWN__UP,
    SS_14_BLOCKED: SS_14_BLOCKED,
    SS_15_STROLL_INTO_AIR: SS_15_STROLL_INTO_AIR,
    SS_16_DESCEND_ONE_STEP: SS_16_DESCEND_ONE_STEP
};
import {
    SW_0_SAME,
    SW_1_UP_UP_CLOCK,
    SW_2_UP_UP_COUNTER,
    SW_3_DOWN_DOWN_CLOCK,
    SW_4_DOWN_DOWN_COUNTER,
    SW_5_FLAT__FLAT,
    SW_6_FLAT__UP,
    SW_7_UP__FLAT,
    SW_8_DOWN__FLAT,
    SW_9_FLAT__DOWN,
    SW_10_UP__UP,
    SW_11_DOWN__DOWN,
    SW_12_UP__DOWN,
    SW_13_DOWN__UP,
    SW_14_BLOCKED,
    SW_15_STROLL_INTO_AIR,
    SW_16_DESCEND_ONE_STEP
} from "../tiles/sw/sw-constants.js";

let sw_move_types = {
    SW_0_SAME: SW_0_SAME,
    SW_1_UP_UP_CLOCK: SW_1_UP_UP_CLOCK,
    SW_2_UP_UP_COUNTER: SW_2_UP_UP_COUNTER,
    SW_3_DOWN_DOWN_CLOCK: SW_3_DOWN_DOWN_CLOCK,
    SW_4_DOWN_DOWN_COUNTER: SW_4_DOWN_DOWN_COUNTER,
    SW_5_FLAT__FLAT: SW_5_FLAT__FLAT,
    SW_6_FLAT__UP: SW_6_FLAT__UP,
    SW_7_UP__FLAT: SW_7_UP__FLAT,
    SW_8_DOWN__FLAT: SW_8_DOWN__FLAT,
    SW_9_FLAT__DOWN: SW_9_FLAT__DOWN,
    SW_10_UP__UP: SW_10_UP__UP,
    SW_11_DOWN__DOWN: SW_11_DOWN__DOWN,
    SW_12_UP__DOWN: SW_12_UP__DOWN,
    SW_13_DOWN__UP: SW_13_DOWN__UP,
    SW_14_BLOCKED: SW_14_BLOCKED,
    SW_15_STROLL_INTO_AIR: SW_15_STROLL_INTO_AIR,
    SW_16_DESCEND_ONE_STEP: SW_16_DESCEND_ONE_STEP
};

let test_move_types = {
    NE: ne_move_types,
    NN: nn_move_types,
    NW: nw_move_types,
    SE: se_move_types,
    SS: ss_move_types,
    SW: sw_move_types
};

export { test_move_types };
